import "../styles/globals.css"
import { Header } from "./components/Header/Header"
import StoreProvider from "./store/StoreProvider"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
            <Header />
            {children}
        </body>
      </html>
    </StoreProvider>
  )
}
